WITH MILK_BUYER AS (
    SELECT DISTINCT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'MILK'
), YOGURT_BUYER AS (
    SELECT DISTINCT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'YOGURT'
)

SELECT *
FROM MILK_BUYER
WHERE CART_ID IN (SELECT *
                  FROM YOGURT_BUYER)