WITH RECURSIVE TREE AS (
    SELECT ID, PARENT_ID, 1 AS DEPTH
    FROM ECOLI_DATA
    WHERE ISNULL(PARENT_ID)
    UNION ALL
    SELECT E.ID, E.PARENT_ID, DEPTH + 1
    FROM ECOLI_DATA AS E
    JOIN TREE AS T
    ON E.PARENT_ID = T.ID
)

SELECT ID
FROM TREE
WHERE DEPTH = 3
ORDER BY ID