WITH HISTORY AS (
    SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT O.USER_ID) AS PURCHASE
    FROM ONLINE_SALE AS O
    JOIN USER_INFO AS U
    ON O.USER_ID = U.USER_ID
    WHERE YEAR(JOINED) = 2021
    GROUP BY YEAR, MONTH
), TOTAL_USER AS (
    SELECT COUNT(DISTINCT USER_ID) AS TOTAL
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)

SELECT YEAR, MONTH, PURCHASE AS PURCHASED_USERS, ROUND(PURCHASE / TOTAL, 1) AS PUCHASED_RATIO
FROM HISTORY
JOIN TOTAL_USER
ORDER BY YEAR, MONTH