WITH VALID_TRIPS AS (
    SELECT T.REQUEST_AT, T.STATUS
    FROM TRIPS AS T
    JOIN USERS AS C ON T.CLIENT_ID = C.USERS_ID AND C.BANNED = 'NO'
    JOIN USERS AS D ON T.DRIVER_ID = D.USERS_ID AND D.BANNED = 'NO'
    WHERE T.REQUEST_AT BETWEEN '2013-10-01' AND '2013-10-03'
), DAILY_STATS AS (
    SELECT REQUEST_AT, COUNT(*) AS TOTAL_COUNT, SUM(CASE
                                                    WHEN STATUS IN ('CANCELLED_BY_CLIENT', 'CANCELLED_BY_DRIVER') THEN 1
                                                    ELSE 0
                                                    END) AS CANCEL_COUNT
    FROM VALID_TRIPS
    GROUP BY REQUEST_AT
)

SELECT REQUEST_AT AS DAY, ROUND(CANCEL_COUNT / TOTAL_COUNT, 2) AS `CANCELLATION RATE`
FROM DAILY_STATS