WITH STADIUM_GRP AS (
    SELECT *, ID - ROW_NUMBER() OVER(ORDER BY ID) AS GRP
    FROM STADIUM
    WHERE PEOPLE >= 100
)

SELECT ID, VISIT_DATE, PEOPLE
FROM STADIUM_GRP
WHERE GRP IN (SELECT GRP
              FROM STADIUM_GRP
              GROUP BY GRP
              HAVING COUNT(*) >= 3)
ORDER BY VISIT_DATE
