SELECT ANIMAL_ID, NAME
FROM (SELECT O.ANIMAL_ID, O.NAME, (O.DATETIME - I.DATETIME) AS DURATION
      FROM ANIMAL_INS AS I
      JOIN ANIMAL_OUTS AS O
      ON I.ANIMAL_ID = O.ANIMAL_ID
      ORDER BY DURATION DESC
      LIMIT 2) AS W
ORDER BY DURATION DESC