WITH NO_RENT_ID AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
), PLAN AS (
    SELECT CAR_TYPE, (DISCOUNT_RATE / 100) AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE IN ('SUV', '세단')
      AND DURATION_TYPE = '30일 이상'
), CAR AS (
    SELECT *
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE IN ('SUV', '세단')
      AND CAR_ID NOT IN (SELECT CAR_ID
                         FROM NO_RENT_ID)
), FEE_CALC AS (
    SELECT CAR_ID, C.CAR_TYPE, CEIL(30 * DAILY_FEE * (1 - DISCOUNT_RATE)) AS FEE
    FROM CAR AS C
    JOIN PLAN AS P
    ON C.CAR_TYPE = P.CAR_TYPE
)

SELECT *
FROM FEE_CALC
WHERE FEE >= 500000 AND FEE <= 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC