SELECT D.ID, (CASE
              WHEN D.PER <= 0.25 THEN 'CRITICAL'
              WHEN D.PER <= 0.50 THEN 'HIGH'
              WHEN D.PER <= 0.75 THEN 'MEDIUM'
              WHEN D.PER <= 1.00 THEN 'LOW'
              END) AS COLONY_NAME
FROM (SELECT ID, PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS PER
      FROM ECOLI_DATA) AS D
ORDER BY D.ID