WITH TARGET AS (
    SELECT *
    FROM APPOINTMENT
    WHERE DATE(APNT_YMD) = '2022-04-13' AND APNT_CNCL_YN = 'N' AND MCDP_CD = 'CS'
)

SELECT APNT_NO, PT_NAME, P.PT_NO, D.MCDP_CD, DR_NAME, APNT_YMD
FROM TARGET AS T
JOIN PATIENT AS P
ON T.PT_NO = P.PT_NO
JOIN DOCTOR AS D
ON T.MDDR_ID = D.DR_ID
ORDER BY APNT_YMD