# Write your MySQL query statement below
# operation      'Sell', 'Buy'

WITH BUY_HISTORY AS (
    SELECT STOCK_NAME, SUM(PRICE) AS BUY_TOTAL
    FROM STOCKS
    WHERE OPERATION = 'BUY'
    GROUP BY STOCK_NAME
), SELL_HISTORY AS (
    SELECT STOCK_NAME, SUM(PRICE) AS SELL_TOTAL
    FROM STOCKS
    WHERE OPERATION = 'SELL'
    GROUP BY STOCK_NAME
)

SELECT B.STOCK_NAME AS stock_name, (SELL_TOTAL - BUY_TOTAL) AS capital_gain_loss
FROM BUY_HISTORY AS B
JOIN SELL_HISTORY AS S
ON B.STOCK_NAME = S.STOCK_NAME