SELECT *,
       CASE
       WHEN DNA_SEQUENCE REGEXP '^ATG' THEN 1
       ELSE 0
       END AS HAS_START,
       CASE
       WHEN DNA_SEQUENCE REGEXP 'TAA$|TAG$|TGA$' THEN 1
       ELSE 0
       END AS HAS_STOP,
       CASE
       WHEN DNA_SEQUENCE REGEXP 'ATAT' THEN 1
       ELSE 0
       END AS HAS_ATAT,
       CASE
       WHEN DNA_SEQUENCE REGEXP 'G{3,}' THEN 1
       ELSE 0
       END AS HAS_GGG
FROM SAMPLES
ORDER BY SAMPLE_ID