WITH RECURSIVE TREE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE ISNULL(PARENT_ID)
    UNION ALL
    SELECT E.ID, E.PARENT_ID, T.GENERATION + 1
    FROM ECOLI_DATA AS E
    JOIN TREE AS T
    ON E.PARENT_ID = T.ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM TREE
WHERE ID NOT IN (SELECT DISTINCT PARENT_ID
                 FROM TREE
                 WHERE NOT ISNULL(PARENT_ID))
GROUP BY GENERATION
ORDER BY GENERATION