SELECT FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS SUM_ORDER
      FROM (SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
            UNION ALL
            SELECT FLAVOR, TOTAL_ORDER FROM JULY) AS T
      GROUP BY FLAVOR
      ORDER BY SUM_ORDER DESC
      LIMIT 3) AS F