WITH HIGH_EARNER AS (
    SELECT DEPARTMENTID, NAME, SALARY, DENSE_RANK() OVER(PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) AS SALARY_RANK
    FROM EMPLOYEE
)

SELECT D.NAME AS DEPARTMENT, H.NAME AS EMPLOYEE, SALARY
FROM DEPARTMENT AS D
JOIN HIGH_EARNER AS H
ON D.ID = H.DEPARTMENTID
WHERE SALARY_RANK <= 3