WITH HISTORY AS (
    SELECT HISTORY_ID, CAR_TYPE, DAILY_FEE, (DATEDIFF(END_DATE, START_DATE) + 1) AS DURATION,
           (CASE
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
            END) AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR AS C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    ON C.CAR_ID = H.CAR_ID
    WHERE CAR_TYPE = '트럭'
), PLAN AS (
    SELECT DURATION_TYPE, (DISCOUNT_RATE / 100) AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
)

SELECT HISTORY_ID, ROUND(DURATION * DAILY_FEE * (1 - IFNULL(DISCOUNT_RATE, 0))) AS FEE
FROM HISTORY AS H
LEFT JOIN PLAN AS P
ON H.DURATION_TYPE = P.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC