WITH RENTAL AS (
    SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) OVER(PARTITION BY CAR_ID) AS TOTAL_COUNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
)
SELECT MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM RENTAL
WHERE TOTAL_COUNT >= 5
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC