SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS AS D
WHERE EXISTS (SELECT 1
             FROM SKILLCODES AS S
             WHERE S.NAME IN ('Python', 'C#') AND
             S.CODE & D.SKILL_CODE != 0)
ORDER BY ID