SELECT CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM (
    SELECT *, MAX(PRICE) OVER(PARTITION BY CATEGORY) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
) AS F
WHERE PRICE = MAX_PRICE
ORDER BY MAX_PRICE DESC