WITH SALARY_INFO AS (
    SELECT D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE, SALARY, RANK() OVER(PARTITION BY D.NAME ORDER BY SALARY DESC) AS SALARY_RANK
    FROM EMPLOYEE AS E
    JOIN DEPARTMENT AS D
    ON E.DEPARTMENTID = D.ID
)

SELECT DEPARTMENT, EMPLOYEE, SALARY
FROM SALARY_INFO
WHERE SALARY_RANK = 1